language: python
matrix:
  include:
    - name: "Python 3.7.3 on Ubuntu 16.0.4"
      os: linux
      python: 3.7.3
      dist: xenial
      sudo: true

    - name: "Python 3.6 on Ubuntu 16.0.4"
      os: linux
      python: 3.6
      dist: xenial
      sudo: true

    - name: "Python 3.7.2 on OSX"
      os: osx
      language: shell
      dist: xcode10.2
      sudo: true

    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

cache: pip
# install dependencies
install:
  - pip3 install --upgrade pip
  #- travis_wait pip3 install -e .
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then travis_wait pip install --no-cache-dir -e .; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then travis_wait pip3 install --no-cache-dir -e .; fi
  - travis_wait pip3 install pytest

before_script: cd tests/ci_tests
# run tests
script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then travis_wait python full_test.py; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then travis_wait python3 full_test.py; fi
  # deploy to pip
  deploy:
    provider: pypi
    user: ""
    password: ""
    on:
      branch: master
    distributions: sdist
