name: Benchmark results check

on:
  pull_request:
    branches:
      - stable

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Assert benchmarks ran and this version is better
        run: |
          git clone 'https://github.com/torokmark/assert.sh'
          cd assert.sh
          source assert.sh
          cd ..
          commit=$(git rev-parse HEAD)
          against="best"
          status=$(curl -X GET http://benchmarks.mindsdb.com:9107/compare/$against/$commit?release_only=True)
          echo Got benchmark status $status between $commit and $against
          assert_eq "$status" "Yes" && echo 'Good to go!'
