name: Lightwood publish to PyPi

on:
  pull_request:
    branches: [ stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2        
    - name: Publish Lightwood
      uses: pypa/gh-action-pypi-publish@v1.3.1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
