name: Lightwood tests workflow

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir --no-use-pep517 -e .
    - name: Lint with flake8
      run: |
        # IMPLEMENT THIS AFTER WE HAVE ALL PEP8 styles
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        cd tests/unit_tests
        python -m unittest
        cd ../..
    - name: Install optional dependencies
      run: |
        pip install --no-cache-dir --no-use-pep517 -r optional_requirements.txt
    - name: Run CI tests
      run: |
        cd tests/ci_tests
        pip -m unittest
        cd ../..
